### ISSUE TITLE
iTag doesn't work with 1.8

### ISSUE THREAD

**Issue by Zwoerni2000** [md-5/iTag#7]
If you run iTag and some one joins there is an exception, because of the changed PacketPlayOutNamedEntitySpawn:
[17:20:21 ERROR]: [iTag] Unhandled exception occured in onPacketSending(PacketEvent) for iTag
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 0, Size: 0)
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:193) ~[ProtocolLib.jar:?]
        at net.md_5.itag.iTag$1.onPacketSending(iTag.java:54) ~[iTag.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:634) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:610) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:362) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:328) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:296) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79) [ProtocolLib.jar:?]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:858) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:328) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:424) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:74) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.EntityTracker.updatePlayers(EntityTracker.java:162) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:775) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:625) [spigot.jar:git-Spigot-"606148f"]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-"606148f"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[17:20:21 ERROR]: Parameters:
  net.minecraft.server.v1_8_R1.PacketPlayOutNamedEntitySpawn@4032a517[
    a=29613
    b=3042ef6c-e43b-47e2-91e6-75f092175f45
    c=-7144
    d=3919
    e=8406
    f=-65
    g=-15
    h=0
    i=net.minecraft.server.v1_8_R1.DataWatcher@40092ca9
    j=<null>
  ]

**Comment by codebucketdev** [comment]
There is a solution how to change the name and skin of a player (http://www.postcrafter.de/viewtopic.php?f=15&t=2387), but is based on hardcoded NMS which I didn't prefer. Also I want to modify the needed packets while sending it to the player. To realise it I want to use ProtocolLib, but I didn't know how to make a use of it..

@md-5 @dmulloy2
